#pragma once

// -----------------------------------------------------------------------------
// AUTO-GENERATED by tools/generate_bindings.py from Interop.h - DO NOT EDIT.
// Regenerate after changing the interop surface: python tools/generate_bindings.py
// -----------------------------------------------------------------------------

#include <sgkit/scripting/Interop.h>

namespace sgkit {
namespace scripting {

struct NativeApi
{
    void  (*Log)(int, const char*);
    int   (*Entity_IsAlive)(unsigned int);
    int   (*Transform_Has)(unsigned int);
    void  (*Transform_GetPosition)(unsigned int, Vec3*);
    void  (*Transform_SetPosition)(unsigned int, const Vec3*);
    void  (*Transform_GetEuler)(unsigned int, Vec3*);
    void  (*Transform_SetEuler)(unsigned int, const Vec3*);
    void  (*Transform_GetScale)(unsigned int, Vec3*);
    void  (*Transform_SetScale)(unsigned int, const Vec3*);
    int   (*Input_IsKeyDown)(int);
    int   (*Input_IsKeyPressed)(int);
    float (*Clock_DeltaTime)();
};

// Point every field at the matching SGK_ function.
inline void FillNativeApi(NativeApi& api)
{
    api.Log                   = &SGK_Log;
    api.Entity_IsAlive        = &SGK_Entity_IsAlive;
    api.Transform_Has         = &SGK_Transform_Has;
    api.Transform_GetPosition = &SGK_Transform_GetPosition;
    api.Transform_SetPosition = &SGK_Transform_SetPosition;
    api.Transform_GetEuler    = &SGK_Transform_GetEuler;
    api.Transform_SetEuler    = &SGK_Transform_SetEuler;
    api.Transform_GetScale    = &SGK_Transform_GetScale;
    api.Transform_SetScale    = &SGK_Transform_SetScale;
    api.Input_IsKeyDown       = &SGK_Input_IsKeyDown;
    api.Input_IsKeyPressed    = &SGK_Input_IsKeyPressed;
    api.Clock_DeltaTime       = &SGK_Clock_DeltaTime;
}

}
}
